name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: "Install build dependencies"
        id: install-deps
        run: |
          sudo apt-get update
          sudo apt-get -y install pkg-config libgtk-4-dev

      - name: "Run cargo fmt"
        id: cargo-fmt
        run: |
          cargo fmt --check

      - name: "Run cargo clippy"
        id: cargo-clippy
        run: |
          cargo clippy -- -Dwarnings


